spring:
  application:
    name: "ms-accounting-transactions"
  devtools:
    add-properties: false
    restart:
      enable: false
  profiles:
    active: dev   #dev, prod
    group:
      dev:
        - "dev"
        - "model-dev"
        - "usecase-dev"
        - "utilities-dev"
        - "rest-dev"
        - "oracle-dev"
        - "rest-client-dev"
      prod:
        - "prod"
        - "model-prod"
        - "usecase-prod"
        - "utilities-prod"
        - "rest-prod"
        - "oracle-prod"
        - "rest-client-prod"